### List clientes
GET http://localhost:3000/firma/1.0.0/enderecos

### Get cliente
GET http://localhost:3000/firma/1.0.0/enderecos/2


### Add cliente
POST http://localhost:3000/firma/1.0.0/enderecos

### Update cliente
PATCH http://localhost:3000/firma/1.0.0/enderecos/1

### delete cliente
DELETE http://localhost:3000/firma/1.0.0/enderecos/1