-- Active: 1739237217105@@127.0.0.1@3306@produtos_db
ALTER TABLE tbl_categoria MODIFY id INT AUTO_INCREMENT;

ALTER TABLE tbl_produtos MODIFY codigo INT AUTO_INCREMENT;

ALTER TABLE tbl_status MODIFY id INT AUTO_INCREMENT;

ALTER TABLE tbl_endereco MODIFY id INT AUTO_INCREMENT;

ALTER TABLE tbl_cliente MODIFY codigo INT AUTO_INCREMENT;

ALTER TABLE tbl_pedido MODIFY numero INT AUTO_INCREMENT;

ALTER TABLE tbl_itempedido MODIFY id INT AUTO_INCREMENT;
